### ISSUE TITLE
How to display information correctly in high dpi ?

### ISSUE THREAD

**Issue by Charltsing** [Lokyyn/Lucid#4]
I test in net8, LucidMessageBox display  incorrect  at high 150% dpi

![1](https://github.com/Lokyyn/Lucid/assets/19963715/f2c56016-a255-469a-ac50-d6cdbada87d6)

ApplicationConfiguration.Initialize();

Lucid.Forms.LucidMessageBox.ShowInformation("Windows 10 1809 or higher is required to run this software!", "Tips");

<img width="172" alt="捕获" src="https://github.com/Lokyyn/Lucid/assets/19963715/548b6c3c-4a2a-4ba6-bc25-eedbc14a1ee9">

maby the window height cannot use a fixed value and should change according to Dpi
![2](https://github.com/Lokyyn/Lucid/assets/19963715/24cc0253-33f3-4fd2-8044-75821c2610d3)

**Comment by Lokyyn** [comment]
Dpi scaling is not an easy problem and it should get fixed right to avoid any other issues resulting from such an change. I also noticed that on 150% scale other controls also have problems with that scaling.

I currently do not plan to support scaling.

**Comment by Charltsing** [comment]
it is my code, modified from darkui        

[DarkMessageBox.zip](https://github.com/Lokyyn/Lucid/files/13809692/DarkMessageBox.zip)

int W = 270;
int H = 130;
int width = (int)(W * Win32.ScreenDPI.OriginalScaleX);
int height = (int)(H * Win32.ScreenDPI.OriginalScaleX);


get OriginalScaleX:
IntPtr hdc = GetDC(IntPtr.Zero);
int DpiX = GetDeviceCaps(hdc, LOGPIXELSX);
ReleaseDC(IntPtr.Zero, hdc);

run before  ApplicationConfiguration.Initialize();
